# Generated by Django 4.2.6 on 2023-10-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField()),
                ('article_date', models.DateTimeField()),
                ('autor', models.CharField(blank=True, max_length=128, null=True)),
                ('url', models.CharField(max_length=1022)),
                ('article_name', models.TextField()),
                ('article_text', models.TextField()),
                ('visitors_count', models.IntegerField()),
                ('is_top_artikle', models.IntegerField()),
                ('screenshot_url', models.CharField(blank=True, max_length=90, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('found_word', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('siteid', models.IntegerField()),
                ('filterwordsid', models.IntegerField()),
                ('tts_enabled', models.IntegerField()),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filterwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.IntegerField(blank=True, null=True)),
                ('word', models.CharField(blank=True, max_length=255, null=True)),
                ('wordalias', models.CharField(blank=True, db_column='wordAlias', max_length=1022, null=True)),
                ('subwordalias', models.CharField(blank=True, max_length=255, null=True)),
                ('stopword', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'filterwords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.IntegerField()),
                ('sms', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sitename', models.CharField(max_length=128, unique=True)),
                ('internal_id', models.IntegerField()),
            ],
            options={
                'db_table': 'sites',
                'managed': False,
            },
        ),
    ]
